---
    environment: production
    chdir: /var/www/staging.fosdem.org/search/website/search/searcher/
    address: 127.0.0.1
    port: 4567
    pid: /home/search/thin.pid
    rackup: /home/search/config.ru
    log: /home/search/thin.log
    max_conns: 200
    timeout: 30
    max_persistent_conns: 120
    daemonize: true
