---
    environment: production
    address: 0.0.0.0
    port: 4567
    pid: ./thin.pid
    rackup: ./prod.ru
    log: /dev/null
    max_conns: 200
    timeout: 30
    max_persistent_conns: 120
    daemonize: true
